project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path('', views.index, name='index'),
    path('success/', views.success, name='success'),
]

project/forms.py
import os
from django import forms


class EmailForm(forms.Form):
    sender = forms.CharField(label='', max_length=200, initial=os.getenv('email'), widget=forms.TextInput(attrs={'placeholder': 'Sender'}))
    recipients = forms.CharField(label='', max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Recipients'}))
    subject = forms.CharField(label='', max_length=200, widget=forms.TextInput(attrs={'placeholder': 'Subject'}))
    message = forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder': 'Message'}))

project/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.contrib import messages 
from . forms import EmailForm


def index(request):
    if request.method == 'POST':
        email_form = EmailForm(request.POST)

        if email_form.is_valid():
            sender = email_form.cleaned_data['sender']

            recipients = email_form.cleaned_data['recipients']
            recipient_list = list(recipients.split(';'))

            subject = email_form.cleaned_data['subject']
            message = email_form.cleaned_data['message']


            try:
                send_mail(subject, message, sender, recipient_list, fail_silently=False)
                return redirect('success')

            except:
                messages.error(request, 'Failed to send message')
                return redirect('/')
        
        else:
                messages.error(request, 'Invalid form data')
                return redirect('/')
            
    else:
        email_form = EmailForm()

        return render(request, 'index.html', {'email_form': email_form})
        

success = lambda request: render(request, 'success.html')

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Email-Send</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-neutral-800 color-white lg:flex lg:items-center lg:justify-center lg:flex-col">
    {% for message in messages %}
        <p class="absolute top-0 text-center bg-red-500 w-full  mb-2  text-white text-xs p-[0.1em]"> {{message}} </p>
    {% endfor %}
    <form method="POST" class="p-6 pt-12 form md:p-12 md:pt-20 lg:w-[70%] lg:rounded-lg ">
        {% csrf_token %}
        {{email_form.as_p}}
        <button class="flex items-center justify-center bg-blue-600 hover:bg-blue-500 rounded-full text-white font-bold text-xl">Submit</button>
    </form>
</body>
<style>
    .form{
        display: grid;
        grid-template-rows: 5% 5% 5% 1fr 8%; 
        row-gap: 1.5%;      
    }
    p > input[type='text']{
        width: 100%;
        background-color: #262626;
        color: white;
        border-bottom: 1px solid gray;
    }
    
    p > input[type='text']:focus, #id_message:focus{
        outline: none;
    }
    
    p > input[type='text']::placeholder, #id_message::placeholder{
        color: gray;
    }
    
    #id_message{
        background-color: #262626;
        color: white;
        font-size: 1rem;
        width: 100%;
        height: 60vh;
        overflow: auto;
        resize: none; 
    }

    @media screen and (min-width: 1024px) {
        p > input[type='text']{
            background-color: #404040;
            padding: 0 .5rem;
        }
        
        #id_message{
            background-color: #404040;
            padding: 0 .5rem;
        }

    }
</style>
</html>

templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="h-screen flex justify-center items-center">
    <div class="flex flex-col items-center text-4xl">
        🚀
        <h1 class="font-extrabold">Message Sent Successfully</h1>
    </div>
</body>
</html>